services:
  ingress:
    image: asia-northeast1-docker.pkg.dev/shiny-on-cloud-run/with-oauth2/ingress:0.1.0
    build:
      context: ingress
      dockerfile: Dockerfile
    environment:
      - OAUTH2_PROXY_HOST=oauth2-proxy
      - BACKEND_HOST=shiny
    ports:
      - 80:8080
  oauth2-proxy:
    image: asia-northeast1-docker.pkg.dev/shiny-on-cloud-run/with-oauth2/oauth2-proxy:v7.6.0
    build:
      context: oauth2-proxy
    environment:
      - OAUTH2_PROXY_COOKIE_SECRET=$OAUTH2_PROXY_COOKIE_SECRET
      - OAUTH2_PROXY_CLIENT_ID=$OAUTH2_PROXY_CLIENT_ID
      - OAUTH2_PROXY_CLIENT_SECRET=$OAUTH2_PROXY_CLIENT_SECRET
      - OAUTH2_PROXY_REVERSE_PROXY=true
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_SET_XAUTHREQUEST=true
      - OAUTH2_PROXY_PASS_ACCESS_TOKEN=true
      - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
      - OAUTH2_PROXY_REDIRECT_URL=http://localhost/oauth2/callback
  shiny:
    image: asia-northeast1-docker.pkg.dev/shiny-on-cloud-run/with-oauth2/shiny:0.1.0
    build:
      context: shiny
      dockerfile: Dockerfile
