apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  # サービス名
  name: shiny-on-cloud-run-with-oauth2
  annotations:
    # ネットワーキング > 上り（内向き）の制御: すべて
    run.googleapis.com/ingress: all
spec:
  template:
    spec:
      # コンテナの定義
      containers:
      # メインコンテナ (Ingress)
      - image: asia-northeast1-docker.pkg.dev/shiny-on-cloud-run/with-oauth2/ingress:0.1.0
        ports:
          - containerPort: 8080
      # サイドカーコンテナ (oauth2-proxy)
      - image: asia-northeast1-docker.pkg.dev/shiny-on-cloud-run/with-oauth2/oauth2-proxy:v7.6.0
        env:
          - name: OAUTH2_PROXY_COOKIE_SECRET
            valueFrom:
              secretKeyRef:
                key: latest
                name: oauth2-proxy-cookie-secret
          - name: OAUTH2_PROXY_CLIENT_ID
            valueFrom:
              secretKeyRef:
                key: latest
                name: oauth2-proxy-client-id
          - name: OAUTH2_PROXY_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                key: latest
                name: oauth2-proxy-client-secret
          - name: OAUTH2_PROXY_REVERSE_PROXY
            value: "true"
          - name: OAUTH2_PROXY_EMAIL_DOMAINS
            value: "*"
          - name: OAUTH2_PROXY_SET_XAUTHREQUEST
            value: "true"
          - name: OAUTH2_PROXY_PASS_ACCESS_TOKEN
            value: "true"
          - name: OAUTH2_PROXY_HTTP_ADDRESS
            value: 0.0.0.0:4180
          - name: OAUTH2_PROXY_REDIRECT_URL
            value: https://shiny-on-cloud-run-with-oauth2-wnhfqqaxta-uc.a.run.app/oauth2/callback
      # サイドカーコンテナ (バックエンド)
      - image: asia-northeast1-docker.pkg.dev/shiny-on-cloud-run/with-oauth2/shiny:0.1.0
